### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hasahmed** [joshmarinacci/AppBundler#5]
Hello, I was wondering what license this is under and wondering if you could add the license file to the repo?

**Comment by joshmarinacci** [comment]
Oh wow. I haven't worked on this in years. I forgot it was still out there. What license would be the most convenient for you? BSD? MIT?

**Comment by hasahmed** [comment]
Thanks for your response! All the open source-ish ones are convenient for me. I like MIT. I am very happy to have found this project, it I think it will make my life much easier.

**Comment by joshmarinacci** [comment]
I've added the MIT license.  Have you used this project yet? I'm curious if it still works with recent versions of Java.

**Comment by hasahmed** [comment]
Thank you! Yeah I tried, and it built the app, but it wouldn't run. The error said that I needed to install java 6 to run it.

**Comment by joshmarinacci** [comment]
Yeah. This is really old code. I don't recommend using it. Somewhere in the Java 7 / JavaFX timeframe they added a packager tool to the JDK. You should use that one instead.

-j

**Comment by hasahmed** [comment]
Cool thanks. I think that is exactly what I'm looking for!
